apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: baraajr11/client:latest
# to create multiple objects in one file, use '---' to separate them
---
apiVersion: v1
kind: Service
metadata:
  name: client-srv
spec:
  selector:
    app: client
  type: ClusterIP # default is ClusterIp so we can delete this line
  ports:
    - name: client
      protocol: TCP
      port: 3000 # this the node port itself
      targetPort: 3000 # our app listens on this port
