apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments
  template:
    metadata:
      labels:
        app: comments
    spec:
      containers:
        - name: comments
          image: baraajr11/comments:latest
# to create multiple objects in one file, use '---' to separate them
---
apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  selector:
    app: comments
  type: ClusterIP # default is ClusterIp so we can delete this line
  ports:
    - name: comments
      protocol: TCP
      port: 4001 # this the node port itself
      targetPort: 4001 # our app listens on this port
