apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus
          image: baraajr11/event-bus:latest
# to create multiple objects in one file, use '---' to separate them
---
apiVersion: v1
kind: Service
metadata:
  name: event-bus-srv
spec:
  selector:
    app: event-bus
  type: ClusterIP # default is ClusterIp so we can delete this line
  ports:
    - name: event-bus
      protocol: TCP
      port: 4005 # this the node port itself
      targetPort: 4005 # our app listens on this port
