apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: baraajr11/moderation:latest
# to create multiple objects in one file, use '---' to separate them
---
apiVersion: v1
kind: Service
metadata:
  name: moderation-srv
spec:
  selector:
    app: moderation
  type: ClusterIP # default is ClusterIp so we can delete this line
  ports:
    - name: moderation
      protocol: TCP
      port: 4003 # this the node port itself
      targetPort: 4003 # our app listens on this port
