apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector: # Selector to match pods managed by this deployment
    matchLabels:
      app: posts
  template: # Pod template for creating pods
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: baraajr11/posts:latest
---
apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector:
    app: posts
  type: ClusterIP # default is ClusterIp so we can delete this line
  ports:
    - name: posts
      protocol: TCP
      port: 4000 # this the node port itself
      targetPort: 4000 # our app listens on this port

