apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: baraajr11/query:latest
# to create multiple objects in one file, use '---' to separate them
---
apiVersion: v1
kind: Service
metadata:
  name: query-srv
spec:
  selector:
    app: query
  type: ClusterIP # default is ClusterIp so we can delete this line
  ports:
    - name: query
      protocol: TCP
      port: 4002 # this the node port itself
      targetPort: 4002 # our app listens on this port
